---

all:
  vars:
    pod_network_cidr: 192.168.32.0/16
    service_network_cidr: 192.168.33.0/16
    master_ip: 192.168.32.42
  children:
    master:
      hosts:
        master-1:
          ip: 192.168.32.42
          ansible_host: 127.0.0.1
          ansible_port: 2342
          ansible_private_key_file: ../.vagrant/machines/master-1/virtualbox/private_key
    minions:
      hosts:
        minion-1:
          ip: 192.168.32.43
          ansible_host: 127.0.0.1
          ansible_port: 2343
          ansible_private_key_file: ../.vagrant/machines/minion-1/virtualbox/private_key
        minion-2:
          ip: 192.168.32.44
          ansible_host: 127.0.0.1
          ansible_port: 2344
          ansible_private_key_file: ../.vagrant/machines/minion-2/virtualbox/private_key
        minion-3:
          ip: 192.168.32.45
          ansible_host: 127.0.0.1
          ansible_port: 2345
          ansible_private_key_file: ../.vagrant/machines/minion-3/virtualbox/private_key