---

all:
  children:
    master:
      hosts:
        master-1:
          ansible_host: 127.0.0.1
          ansible_port: 2342
          ansible_private_key_file: ../.vagrant/machines/master-1/virtualbox/private_key
    minions:
      hosts:
        minion-:
          ansible_host: 127.0.0.1
          ansible_port: 2343
          ansible_private_key_file: ../.vagrant/machines/minion-1/virtualbox/private_key
        minion-2:
          ansible_host: 127.0.0.1
          ansible_port: 2344
          ansible_private_key_file: ../.vagrant/machines/minion-2/virtualbox/private_key
        minion-3:
          ansible_host: 127.0.0.1
          ansible_port: 2345
          ansible_private_key_file: ../.vagrant/machines/minion-3/virtualbox/private_key