---

- name: Create the .kube directory
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant


- name: Copy kube config to .kube
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: True
    owner: vagrant
    group: vagrant
    mode: 0644
  become: True


