---

- name: Initialize the cluster
  import_tasks: init_cluster.yml

- name: Configure .kube directory for kubectl
  import_tasks: configure_kubectl.yml

- name: Install and configure calico
  import_tasks: calico.yml

- name: Install and configure the admin dashboard
  import_tasks: admin_dashboard.yml

- name: Install helm and tiller in the master
  import_tasks: helm.yml

- name: Install and configure storageOS
  import_tasks: storageos.yml

