---

- name: Common steps on all the nodes
  hosts: all
  roles:
    - common
  become: True
  become_user: root

- name: Configure the master nodes
  hosts: master
  roles:
    - master

- name: Configure the minions
  hosts: minions
  roles:
    - minion
  become: True
  become_user: root


- name: Configure StorageOS
  hosts: master
  roles:
    - storageos