---

- name: Hello world on all nodes
  hosts: all
  roles:
    - common
  become: True
  become_user: root

- name: Hello world on master
  hosts: master
  roles:
    - master

- name: Hello world on minions
  hosts: minions
  roles:
    - minion
  become: True
  become_user: root